apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

# ---------------------- notes ---------------------------------
# built-in default scaleup & scaledown cooldown period(CDP) on HPA kubernetes cant be changed
# scaleup CDP around 3mins (tested)
# scaledown CDP around 5mins (tested)
# source : https://stackoverflow.com/questions/64523941/kubernetes-hpa-scale-up-cooldown
# 