apiVersion: v1
kind: Service
metadata:
  name: metrics-server-nodeport
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 443
      nodePort: 30000
  selector:
    k8s-app: metrics-server