apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  #namespace: app
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  type: NodePort        # Change this line to specify the service type as NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111     # Specify the nodePort value you want to use
  selector:
    run: php-apache